name: Deploy to Docker Hub and Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Image Tag
        run: echo "IMAGE_TAG=${{ secrets.DOCKER_USERNAME }}/my-static-site:$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build Docker Image
        run: docker build -t $IMAGE_TAG .

      - name: Push Docker Image to Docker Hub
        run: |
          docker push $IMAGE_TAG
          docker tag $IMAGE_TAG ${{ secrets.DOCKER_USERNAME }}/my-static-site:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/my-static-site:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: SSH into Remote Server and Deploy
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.REMOTE_SERVER_IP }}
          username: ${{ secrets.REMOTE_SERVER_USERNAME }}
          key: ${{ secrets.REMOTE_SERVER_PRIVATE_KEY }}
          port: 22
          script: |
            # Pull the latest Docker image from Docker Hub
            docker pull $IMAGE_TAG
            # Stop and remove the current container (if running)
            docker stop my-static-site || true
            docker rm my-static-site || true
            # Run the new container with the latest image
            docker run -d --name my-static-site -p 80:80 $IMAGE_TAG
